/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-29 at 15:09:05 UTC 
 * Modify at your own risk.
 */

package com.example.phonebook.contactendpoint.model;

/**
 * Model definition for Contact.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the contactendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Contact extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contactFirstName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long contactId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contactLastName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contactPhoneNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContactFirstName() {
    return contactFirstName;
  }

  /**
   * @param contactFirstName contactFirstName or {@code null} for none
   */
  public Contact setContactFirstName(java.lang.String contactFirstName) {
    this.contactFirstName = contactFirstName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getContactId() {
    return contactId;
  }

  /**
   * @param contactId contactId or {@code null} for none
   */
  public Contact setContactId(java.lang.Long contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContactLastName() {
    return contactLastName;
  }

  /**
   * @param contactLastName contactLastName or {@code null} for none
   */
  public Contact setContactLastName(java.lang.String contactLastName) {
    this.contactLastName = contactLastName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContactPhoneNumber() {
    return contactPhoneNumber;
  }

  /**
   * @param contactPhoneNumber contactPhoneNumber or {@code null} for none
   */
  public Contact setContactPhoneNumber(java.lang.String contactPhoneNumber) {
    this.contactPhoneNumber = contactPhoneNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Contact setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public Contact setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public Contact set(String fieldName, Object value) {
    return (Contact) super.set(fieldName, value);
  }

  @Override
  public Contact clone() {
    return (Contact) super.clone();
  }

}
