/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-29 at 15:09:05 UTC 
 * Modify at your own risk.
 */

package com.example.phonebook.contactendpoint;

/**
 * Service definition for Contactendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ContactendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Contactendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the contactendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://phonebookexample.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "contactendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Contactendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Contactendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getContact".
   *
   * This request holds the parameters needed by the the contactendpoint server.  After setting any
   * optional parameters, call the {@link GetContact#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetContact getContact(java.lang.Long id) throws java.io.IOException {
    GetContact result = new GetContact(id);
    initialize(result);
    return result;
  }

  public class GetContact extends ContactendpointRequest<com.example.phonebook.contactendpoint.model.Contact> {

    private static final String REST_PATH = "contact/{id}";

    /**
     * Create a request for the method "getContact".
     *
     * This request holds the parameters needed by the the contactendpoint server.  After setting any
     * optional parameters, call the {@link GetContact#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetContact#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetContact(java.lang.Long id) {
      super(Contactendpoint.this, "GET", REST_PATH, null, com.example.phonebook.contactendpoint.model.Contact.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetContact setAlt(java.lang.String alt) {
      return (GetContact) super.setAlt(alt);
    }

    @Override
    public GetContact setFields(java.lang.String fields) {
      return (GetContact) super.setFields(fields);
    }

    @Override
    public GetContact setKey(java.lang.String key) {
      return (GetContact) super.setKey(key);
    }

    @Override
    public GetContact setOauthToken(java.lang.String oauthToken) {
      return (GetContact) super.setOauthToken(oauthToken);
    }

    @Override
    public GetContact setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetContact) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetContact setQuotaUser(java.lang.String quotaUser) {
      return (GetContact) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetContact setUserIp(java.lang.String userIp) {
      return (GetContact) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetContact setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetContact set(String parameterName, Object value) {
      return (GetContact) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertContact".
   *
   * This request holds the parameters needed by the the contactendpoint server.  After setting any
   * optional parameters, call the {@link InsertContact#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.phonebook.contactendpoint.model.Contact}
   * @return the request
   */
  public InsertContact insertContact(com.example.phonebook.contactendpoint.model.Contact content) throws java.io.IOException {
    InsertContact result = new InsertContact(content);
    initialize(result);
    return result;
  }

  public class InsertContact extends ContactendpointRequest<com.example.phonebook.contactendpoint.model.Contact> {

    private static final String REST_PATH = "contact";

    /**
     * Create a request for the method "insertContact".
     *
     * This request holds the parameters needed by the the contactendpoint server.  After setting any
     * optional parameters, call the {@link InsertContact#execute()} method to invoke the remote
     * operation. <p> {@link InsertContact#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.phonebook.contactendpoint.model.Contact}
     * @since 1.13
     */
    protected InsertContact(com.example.phonebook.contactendpoint.model.Contact content) {
      super(Contactendpoint.this, "POST", REST_PATH, content, com.example.phonebook.contactendpoint.model.Contact.class);
    }

    @Override
    public InsertContact setAlt(java.lang.String alt) {
      return (InsertContact) super.setAlt(alt);
    }

    @Override
    public InsertContact setFields(java.lang.String fields) {
      return (InsertContact) super.setFields(fields);
    }

    @Override
    public InsertContact setKey(java.lang.String key) {
      return (InsertContact) super.setKey(key);
    }

    @Override
    public InsertContact setOauthToken(java.lang.String oauthToken) {
      return (InsertContact) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertContact setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertContact) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertContact setQuotaUser(java.lang.String quotaUser) {
      return (InsertContact) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertContact setUserIp(java.lang.String userIp) {
      return (InsertContact) super.setUserIp(userIp);
    }

    @Override
    public InsertContact set(String parameterName, Object value) {
      return (InsertContact) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listContact".
   *
   * This request holds the parameters needed by the the contactendpoint server.  After setting any
   * optional parameters, call the {@link ListContact#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListContact listContact() throws java.io.IOException {
    ListContact result = new ListContact();
    initialize(result);
    return result;
  }

  public class ListContact extends ContactendpointRequest<com.example.phonebook.contactendpoint.model.CollectionResponseContact> {

    private static final String REST_PATH = "contact";

    /**
     * Create a request for the method "listContact".
     *
     * This request holds the parameters needed by the the contactendpoint server.  After setting any
     * optional parameters, call the {@link ListContact#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListContact#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListContact() {
      super(Contactendpoint.this, "GET", REST_PATH, null, com.example.phonebook.contactendpoint.model.CollectionResponseContact.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListContact setAlt(java.lang.String alt) {
      return (ListContact) super.setAlt(alt);
    }

    @Override
    public ListContact setFields(java.lang.String fields) {
      return (ListContact) super.setFields(fields);
    }

    @Override
    public ListContact setKey(java.lang.String key) {
      return (ListContact) super.setKey(key);
    }

    @Override
    public ListContact setOauthToken(java.lang.String oauthToken) {
      return (ListContact) super.setOauthToken(oauthToken);
    }

    @Override
    public ListContact setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListContact) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListContact setQuotaUser(java.lang.String quotaUser) {
      return (ListContact) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListContact setUserIp(java.lang.String userIp) {
      return (ListContact) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListContact setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListContact setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListContact set(String parameterName, Object value) {
      return (ListContact) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeContact".
   *
   * This request holds the parameters needed by the the contactendpoint server.  After setting any
   * optional parameters, call the {@link RemoveContact#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveContact removeContact(java.lang.Long id) throws java.io.IOException {
    RemoveContact result = new RemoveContact(id);
    initialize(result);
    return result;
  }

  public class RemoveContact extends ContactendpointRequest<Void> {

    private static final String REST_PATH = "contact/{id}";

    /**
     * Create a request for the method "removeContact".
     *
     * This request holds the parameters needed by the the contactendpoint server.  After setting any
     * optional parameters, call the {@link RemoveContact#execute()} method to invoke the remote
     * operation. <p> {@link RemoveContact#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveContact(java.lang.Long id) {
      super(Contactendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveContact setAlt(java.lang.String alt) {
      return (RemoveContact) super.setAlt(alt);
    }

    @Override
    public RemoveContact setFields(java.lang.String fields) {
      return (RemoveContact) super.setFields(fields);
    }

    @Override
    public RemoveContact setKey(java.lang.String key) {
      return (RemoveContact) super.setKey(key);
    }

    @Override
    public RemoveContact setOauthToken(java.lang.String oauthToken) {
      return (RemoveContact) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveContact setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveContact) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveContact setQuotaUser(java.lang.String quotaUser) {
      return (RemoveContact) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveContact setUserIp(java.lang.String userIp) {
      return (RemoveContact) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveContact setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveContact set(String parameterName, Object value) {
      return (RemoveContact) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateContact".
   *
   * This request holds the parameters needed by the the contactendpoint server.  After setting any
   * optional parameters, call the {@link UpdateContact#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.phonebook.contactendpoint.model.Contact}
   * @return the request
   */
  public UpdateContact updateContact(com.example.phonebook.contactendpoint.model.Contact content) throws java.io.IOException {
    UpdateContact result = new UpdateContact(content);
    initialize(result);
    return result;
  }

  public class UpdateContact extends ContactendpointRequest<com.example.phonebook.contactendpoint.model.Contact> {

    private static final String REST_PATH = "contact";

    /**
     * Create a request for the method "updateContact".
     *
     * This request holds the parameters needed by the the contactendpoint server.  After setting any
     * optional parameters, call the {@link UpdateContact#execute()} method to invoke the remote
     * operation. <p> {@link UpdateContact#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.phonebook.contactendpoint.model.Contact}
     * @since 1.13
     */
    protected UpdateContact(com.example.phonebook.contactendpoint.model.Contact content) {
      super(Contactendpoint.this, "PUT", REST_PATH, content, com.example.phonebook.contactendpoint.model.Contact.class);
    }

    @Override
    public UpdateContact setAlt(java.lang.String alt) {
      return (UpdateContact) super.setAlt(alt);
    }

    @Override
    public UpdateContact setFields(java.lang.String fields) {
      return (UpdateContact) super.setFields(fields);
    }

    @Override
    public UpdateContact setKey(java.lang.String key) {
      return (UpdateContact) super.setKey(key);
    }

    @Override
    public UpdateContact setOauthToken(java.lang.String oauthToken) {
      return (UpdateContact) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateContact setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateContact) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateContact setQuotaUser(java.lang.String quotaUser) {
      return (UpdateContact) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateContact setUserIp(java.lang.String userIp) {
      return (UpdateContact) super.setUserIp(userIp);
    }

    @Override
    public UpdateContact set(String parameterName, Object value) {
      return (UpdateContact) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Contactendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Contactendpoint}. */
    @Override
    public Contactendpoint build() {
      return new Contactendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ContactendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setContactendpointRequestInitializer(
        ContactendpointRequestInitializer contactendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(contactendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
